### ISSUE TITLE
مشکل در ریست ترافیک یوزرها

### ISSUE THREAD

**Issue by hayousef68** [Gozargah/Marzban#1064]
سلام از دیروز خیلی از یوزرهام که پیام میدن برای تمدید نمیتونم ترافیک رو ریست کنم خطا میده ( بازنشانی مصرف انجام نشد، دوباره تلاش کنید)

سرور رو عوض کردن مرزبان رو ریستارت کردم بازم درست نشد میشه راهنمایی کنین
![8eeddc35-47b5-45ee-b72e-abd312e2f523](https://github.com/Gozargah/Marzban/assets/144268484/2c126439-a46f-46ad-83b6-632ce76ac0e0)

**Comment by M03ED** [comment]
لاگ مرزبان رو ارسال کنید

**Comment by hayousef68** [comment]
> لاگ مرزبان رو ارسال کنید

marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
marzban-1  |     raise exception
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
marzban-1  |     self.dialect.do_execute(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
marzban-1  |     cursor.execute(statement, parameters)
marzban-1  | sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
marzban-1  | [SQL: INSERT INTO node_usages (created_at, node_id, uplink, downlink) VALUES (?, ?, ?, ?)]
marzban-1  | [parameters: ('2024-07-02 11:00:00.000000', None, 0, 0)]
marzban-1  | (Background on this error at: https://sqlalche.me/e/14/4xp6)

**Comment by hayousef68** [comment]
> لاگ مرزبان رو ارسال کنید

marzban-1  | (Background on this error at: https://sqlalche.me/e/14/4xp6)
marzban-1  | Job "record_node_usages (trigger: interval[0:00:10], next run at: 2024-07-02 11:14:30 UTC)" raised an exception
marzban-1  | Traceback (most recent call last):
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
marzban-1  |     self.dialect.do_execute(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
marzban-1  |     cursor.execute(statement, parameters)
marzban-1  | sqlite3.DatabaseError: database disk image is malformed
marzban-1  | 
marzban-1  | The above exception was the direct cause of the following exception:
marzban-1  | 
marzban-1  | Traceback (most recent call last):
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
marzban-1  |     retval = job.func(*job.args, **job.kwargs)
marzban-1  |   File "/code/app/jobs/record_usages.py", line 195, in record_node_usages
marzban-1  |     record_node_stats(params, node_id)
marzban-1  |   File "/code/app/jobs/record_usages.py", line 94, in record_node_stats
marzban-1  |     safe_execute(db, stmt)
marzban-1  |   File "/code/app/jobs/record_usages.py", line 38, in safe_execute
marzban-1  |     db.execute(stmt, params)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
marzban-1  |     result = conn._execute_20(statement, params or {}, execution_options)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
marzban-1  |     return meth(self, args_10style, kwargs_10style, execution_options)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
marzban-1  |     return connection._execute_clauseelement(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
marzban-1  |     ret = self._execute_context(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
marzban-1  |     self._handle_dbapi_exception(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
marzban-1  |     util.raise_(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
marzban-1  |     raise exception
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
marzban-1  |     self.dialect.do_execute(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
marzban-1  |     cursor.execute(statement, parameters)
marzban-1  | sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
marzban-1  | [SQL: INSERT INTO node_usages (created_at, node_id, uplink, downlink) VALUES (?, ?, ?, ?)]
marzban-1  | [parameters: ('2024-07-02 11:00:00.000000', None, 0, 0)]
marzban-1  | (Background on this error at: https://sqlalche.me/e/14/4xp6)

**Comment by hayousef68** [comment]
> دیتابیس تون به مشکل خورده
راه حلش چیه مهندس چجوری رفع کنم

**Comment by hayousef68** [comment]
> دیتابیس تون به مشکل خورده

چطوری حلش کنم عزیز

**Comment by M03ED** [comment]
راهی برای حل این مشکل وجود نداره ، اگر میتونید یوزر ها تون رو ببینید اون ها رو به یک پنل دیگه منتقل کنید

**Comment by m0x61h0x64i** [comment]
منم این مشکل دارم
marzban-1     | Execution of job "record_node_usages (trigger: interval[0:00:10], next run at: 2024-07-05 20:57:52 UTC)" skipped: maximum number of running instances reached (1)

**Comment by m0x61h0x64i** [comment]
ولی من ریست میتونم بکنم. فقط توی لاگ ارور دارم
reeee's usage has reset successfully.

**Comment by m0x61h0x64i** [comment]
لاگ پر اروره

**Comment by m0x61h0x64i** [comment]
![image](https://github.com/Gozargah/Marzban/assets/109550653/0a00cb5d-1002-4361-a905-806d23730b06)
![image](https://github.com/Gozargah/Marzban/assets/109550653/aacc580e-2716-4db0-a644-254e498d9fc9)
![image](https://github.com/Gozargah/Marzban/assets/109550653/647dc811-14d2-455c-a23b-017b21b48fac)
![image](https://github.com/Gozargah/Marzban/assets/109550653/5a29a7d8-4c81-4b6e-85db-97535217649d)
![image](https://github.com/Gozargah/Marzban/assets/109550653/924dc4a6-87aa-4cfc-a210-0b20fec264e4)
![image](https://github.com/Gozargah/Marzban/assets/109550653/7fd52bc9-db69-4637-85a9-563c60f84caa)
