### ISSUE TITLE
Wrong ALPN for v2ray share links

### ISSUE THREAD

**Issue by fodhelper** [Gozargah/Marzban#1083]
![image](https://github.com/Gozargah/Marzban/assets/161948085/f046dc60-409e-4b31-afa0-c3ba5f16c5b9)

https://github.com/Gozargah/Marzban/blob/ba66057984813a77f56dcc9cd6d2eb6e247c2a3c/app/subscription/share.py#L317

**Comment by fodhelper** [comment]
Internal Error for Clash-Meta
```
INFO:     ---:0 - "GET /---/clash-meta HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/code/app/views/subscription.py", line 228, in user_subscription_with_client_type
    conf = generate_subscription(user=user, config_format="clash-meta", as_base64=False)
  File "/code/app/subscription/share.py", line 148, in generate_subscription
    config = generate_clash_subscription(**kwargs, is_meta=True)
  File "/code/app/subscription/share.py", line 59, in generate_clash_subscription
    return process_inbounds_and_tags(
  File "/code/app/subscription/share.py", line 328, in process_inbounds_and_tags
    conf.add(
  File "/code/app/subscription/clash.py", line 270, in add
    node = self.make_node(
  File "/code/app/subscription/clash.py", line 245, in make_node
    node = super().make_node(
  File "/code/app/subscription/clash.py", line 125, in make_node
    node['alpn'] = alpn.split(',')
AttributeError: 'list' object has no attribute 'split'
```

**Comment by fodhelper** [comment]
ALPN is correct for v2ray-json and sing-box
Problem is only for Clash.Meta and v2ray share links
