### ISSUE TITLE
مشاهده خطا در marzban Logs

### ISSUE THREAD

**Issue by KAJOOSH** [Gozargah/Marzban#1087]
سلام
وقتی marzban logs رو اجرا می کنم هر چند ثانیه این خطاها ظاهر می شود و متوجه مشکل نشدم:
```
xception in thread Thread-33587 (record_user_usage):
marzban-marzban-1     | Traceback (most recent call last):
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1880, in _execute_context
marzban-marzban-1     |     self.dialect.do_executemany(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 193, in do_executemany
marzban-marzban-1     |     rowcount = cursor.executemany(statement, parameters)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 187, in executemany
marzban-marzban-1     |     return self._do_execute_many(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 225, in _do_execute_many
marzban-marzban-1     |     rows += self.execute(sql + postfix)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
marzban-marzban-1     |     result = self._query(query)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
marzban-marzban-1     |     conn.query(q)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
marzban-marzban-1     |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
marzban-marzban-1     |     result.read()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
marzban-marzban-1     |     first_packet = self.connection._read_packet()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
marzban-marzban-1     |     packet.raise_for_error()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
marzban-marzban-1     |     err.raise_mysql_exception(self._data)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
marzban-marzban-1     |     raise errorclass(errno, errval)
marzban-marzban-1     | pymysql.err.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')
marzban-marzban-1     | 
marzban-marzban-1     | 
marzban-marzban-1     | The above exception was the direct cause of the following exception:
marzban-marzban-1     | 
marzban-marzban-1     | 
marzban-marzban-1     | Traceback (most recent call last):
marzban-marzban-1     |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
marzban-marzban-1     |     self.run()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
marzban-marzban-1     |     self._target(*self._args, **self._kwargs)
marzban-marzban-1     |   File "/code/app/jobs/record_usages.py", line 111, in record_user_usage
marzban-marzban-1     |     record_user_stats(params, node_id)
marzban-marzban-1     |   File "/code/app/jobs/record_usages.py", line 42, in record_user_stats
marzban-marzban-1     |     db.execute(stmt, [{'uid': uid} for uid in uids_to_insert])
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
marzban-marzban-1     |     result = conn._execute_20(statement, params or {}, execution_options)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
marzban-marzban-1     |     return meth(self, args_10style, kwargs_10style, execution_options)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
marzban-marzban-1     |     return connection._execute_clauseelement(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
marzban-marzban-1     |     ret = self._execute_context(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
marzban-marzban-1     |     self._handle_dbapi_exception(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
marzban-marzban-1     |     util.raise_(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
marzban-marzban-1     |     raise exception
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1880, in _execute_context
marzban-marzban-1     |     self.dialect.do_executemany(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 193, in do_executemany
marzban-marzban-1     |     rowcount = cursor.executemany(statement, parameters)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 187, in executemany
marzban-marzban-1     |     return self._do_execute_many(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 225, in _do_execute_many
marzban-marzban-1     |     rows += self.execute(sql + postfix)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
marzban-marzban-1     |     result = self._query(query)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
marzban-marzban-1     |     conn.query(q)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
marzban-marzban-1     |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
marzban-marzban-1     |     result.read()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
marzban-marzban-1     |     first_packet = self.connection._read_packet()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
marzban-marzban-1     |     packet.raise_for_error()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
marzban-marzban-1     |     err.raise_mysql_exception(self._data)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
marzban-marzban-1     |     raise errorclass(errno, errval)
marzban-marzban-1     | sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1213, 'Deadlock found when trying to get lock; try restarting transaction')
marzban-marzban-1     | [SQL: INSERT INTO node_user_usages (created_at, user_id, node_id, used_traffic) VALUES (%(created_at)s, %(uid)s, %(node_id)s, %(used_traffic)s)]
marzban-marzban-1     | [parameters: ({'created_at': datetime.datetime(2024, 7, 3, 20, 0), 'uid': 1890, 'node_id': 17, 'used_traffic': 0}, {'created_at': datetime.datetime(2024, 7, 3, 20, 0), 'uid': 1199, 'node_id': 17, 'used_traffic': 0})]
marzban-marzban-1     | (Background on this error at: https://sqlalche.me/e/14/e3q8)
marzban-marzban-1     | Exception in thread Thread-33591 (record_user_usage):
marzban-marzban-1     | Traceback (most recent call last):
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1880, in _execute_context
marzban-marzban-1     |     self.dialect.do_executemany(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 193, in do_executemany
marzban-marzban-1     |     rowcount = cursor.executemany(statement, parameters)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 187, in executemany
marzban-marzban-1     |     return self._do_execute_many(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 225, in _do_execute_many
marzban-marzban-1     |     rows += self.execute(sql + postfix)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
marzban-marzban-1     |     result = self._query(query)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
marzban-marzban-1     |     conn.query(q)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
marzban-marzban-1     |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
marzban-marzban-1     |     result.read()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
marzban-marzban-1     |     first_packet = self.connection._read_packet()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
marzban-marzban-1     |     packet.raise_for_error()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
marzban-marzban-1     |     err.raise_mysql_exception(self._data)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
marzban-marzban-1     |     raise errorclass(errno, errval)
marzban-marzban-1     | pymysql.err.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')
marzban-marzban-1     | 
marzban-marzban-1     | 
marzban-marzban-1     | The above exception was the direct cause of the following exception:
marzban-marzban-1     | 
marzban-marzban-1     | 
marzban-marzban-1     | Traceback (most recent call last):
marzban-marzban-1     |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
marzban-marzban-1     |     self.run()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
marzban-marzban-1     |     self._target(*self._args, **self._kwargs)
marzban-marzban-1     |   File "/code/app/jobs/record_usages.py", line 111, in record_user_usage
marzban-marzban-1     |     record_user_stats(params, node_id)
marzban-marzban-1     |   File "/code/app/jobs/record_usages.py", line 42, in record_user_stats
marzban-marzban-1     |     db.execute(stmt, [{'uid': uid} for uid in uids_to_insert])
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
marzban-marzban-1     |     result = conn._execute_20(statement, params or {}, execution_options)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
marzban-marzban-1     |     return meth(self, args_10style, kwargs_10style, execution_options)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
marzban-marzban-1     |     return connection._execute_clauseelement(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
marzban-marzban-1     |     ret = self._execute_context(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
marzban-marzban-1     |     self._handle_dbapi_exception(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
marzban-marzban-1     |     util.raise_(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
marzban-marzban-1     |     raise exception
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1880, in _execute_context
marzban-marzban-1     |     self.dialect.do_executemany(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 193, in do_executemany
marzban-marzban-1     |     rowcount = cursor.executemany(statement, parameters)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 187, in executemany
marzban-marzban-1     |     return self._do_execute_many(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 225, in _do_execute_many
marzban-marzban-1     |     rows += self.execute(sql + postfix)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
marzban-marzban-1     |     result = self._query(query)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
marzban-marzban-1     |     conn.query(q)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
marzban-marzban-1     |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
marzban-marzban-1     |     result.read()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
marzban-marzban-1     |     first_packet = self.connection._read_packet()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
marzban-marzban-1     |     packet.raise_for_error()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
marzban-marzban-1     |     err.raise_mysql_exception(self._data)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
marzban-marzban-1     |     raise errorclass(errno, errval)
marzban-marzban-1     | sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1213, 'Deadlock found when trying to get lock; try restarting transaction')
marzban-marzban-1     | [SQL: INSERT INTO node_user_usages (created_at, user_id, node_id, used_traffic) VALUES (%(created_at)s, %(uid)s, %(node_id)s, %(used_traffic)s)]
marzban-marzban-1     | [parameters: ({'created_at': datetime.datetime(2024, 7, 3, 20, 0), 'uid': 2001, 'node_id': 145, 'used_traffic': 0}, {'created_at': datetime.datetime(2024, 7, 3, 20, 0), 'uid': 1890, 'node_id': 145, 'used_traffic': 0}, {'created_at': datetime.datetime(2024, 7, 3, 20, 0), 'uid': 1199, 'node_id': 145, 'used_traffic': 0})]
marzban-marzban-1     | (Background on this error at: https://sqlalche.me/e/14/e3q8)
marzban-marzban-1     | Exception in thread Thread-33593 (record_user_usage):
marzban-marzban-1     | Traceback (most recent call last):
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1880, in _execute_context
marzban-marzban-1     |     self.dialect.do_executemany(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 193, in do_executemany
marzban-marzban-1     |     rowcount = cursor.executemany(statement, parameters)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 187, in executemany
marzban-marzban-1     |     return self._do_execute_many(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 225, in _do_execute_many
marzban-marzban-1     |     rows += self.execute(sql + postfix)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
marzban-marzban-1     |     result = self._query(query)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
marzban-marzban-1     |     conn.query(q)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
marzban-marzban-1     |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
marzban-marzban-1     |     result.read()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
marzban-marzban-1     |     first_packet = self.connection._read_packet()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
marzban-marzban-1     |     packet.raise_for_error()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
marzban-marzban-1     |     err.raise_mysql_exception(self._data)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
marzban-marzban-1     |     raise errorclass(errno, errval)
marzban-marzban-1     | pymysql.err.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')
marzban-marzban-1     | 
marzban-marzban-1     | 
marzban-marzban-1     | The above exception was the direct cause of the following exception:
marzban-marzban-1     | 
marzban-marzban-1     | 
marzban-marzban-1     | Traceback (most recent call last):
marzban-marzban-1     |   File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
marzban-marzban-1     |     self.run()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/threading.py", line 953, in run
marzban-marzban-1     |     self._target(*self._args, **self._kwargs)
marzban-marzban-1     |   File "/code/app/jobs/record_usages.py", line 111, in record_user_usage
marzban-marzban-1     |     record_user_stats(params, node_id)
marzban-marzban-1     |   File "/code/app/jobs/record_usages.py", line 42, in record_user_stats
marzban-marzban-1     |     db.execute(stmt, [{'uid': uid} for uid in uids_to_insert])
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
marzban-marzban-1     |     result = conn._execute_20(statement, params or {}, execution_options)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
marzban-marzban-1     |     return meth(self, args_10style, kwargs_10style, execution_options)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
marzban-marzban-1     |     return connection._execute_clauseelement(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
marzban-marzban-1     |     ret = self._execute_context(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
marzban-marzban-1     |     self._handle_dbapi_exception(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
marzban-marzban-1     |     util.raise_(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
marzban-marzban-1     |     raise exception
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1880, in _execute_context
marzban-marzban-1     |     self.dialect.do_executemany(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/mysql/mysqldb.py", line 193, in do_executemany
marzban-marzban-1     |     rowcount = cursor.executemany(statement, parameters)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 187, in executemany
marzban-marzban-1     |     return self._do_execute_many(
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 225, in _do_execute_many
marzban-marzban-1     |     rows += self.execute(sql + postfix)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 158, in execute
marzban-marzban-1     |     result = self._query(query)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/cursors.py", line 325, in _query
marzban-marzban-1     |     conn.query(q)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 549, in query
marzban-marzban-1     |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 779, in _read_query_result
marzban-marzban-1     |     result.read()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 1157, in read
marzban-marzban-1     |     first_packet = self.connection._read_packet()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
marzban-marzban-1     |     packet.raise_for_error()
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
marzban-marzban-1     |     err.raise_mysql_exception(self._data)
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
marzban-marzban-1     |     raise errorclass(errno, errval)
marzban-marzban-1     | sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1213, 'Deadlock found when trying to get lock; try restarting transaction')
marzban-marzban-1     | [SQL: INSERT INTO node_user_usages (created_at, user_id, node_id, used_traffic) VALUES (%(created_at)s, %(uid)s, %(node_id)s, %(used_traffic)s)]
marzban-marzban-1     | [parameters: ({'created_at': datetime.datetime(2024, 7, 3, 20, 0), 'uid': 1890, 'node_id': 139, 'used_traffic': 0}, {'created_at': datetime.datetime(2024, 7, 3, 20, 0), 'uid': 1199, 'node_id': 139, 'used_traffic': 0})]
marzban-marzban-1     | (Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by arian24b** [comment]
سلام
چه نسخه ای رو استفاده میکنین؟
یک بار این دستورات رو بزنین و چک کنین مشکل همچنان هست یا نه:
‍‍‍```
marzban restart
```
