### ISSUE TITLE
باگ ربات تلگرامی

### ISSUE THREAD

**Issue by LonUp** [Gozargah/Marzban#1307]
مشکل عدم نمایش اطلاعات و منیج کردن کاربر در ربات تلگرامی هنگامی که کاربر در حالت  limit حجم قرار داره
در حالت اتمام زمان اشتراک یا on_hold - active و موارد دیگه این مشکل وجود نداره

https://github.com/user-attachments/assets/00d6ed9d-2f1b-4e49-9a80-5b4b2b002a39

 - ; اخرین نسخه دولوپر مرزبان
 - OS: ubuntu 22

**Comment by M03ED** [comment]
لاگ مرزبان رو ارسال کنید

**Comment by LonUp** [comment]
> لاگ مرزبان رو ارسال کنید


هنگامی که سرچ میکنم و پاسخی نمیده دقیقا این لاگ میوفته
```
marzban-1     | 2024-09-07 00:28:14,601 (__init__.py:960 Thread-1 (infinity_polling)) ERROR - TeleBot: "Infinity polling exception: math domain error"
marzban-1     | 2024-09-07 00:28:14,601 (__init__.py:962 Thread-1 (infinity_polling)) ERROR - TeleBot: "Exception traceback:
marzban-1     | Traceback (most recent call last):
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/telebot/__init__.py", line 955, in infinity_polling
marzban-1     |     self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/telebot/__init__.py", line 1043, in polling
marzban-1     |     self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/telebot/__init__.py", line 1118, in __threaded_polling
marzban-1     |     raise e
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/telebot/__init__.py", line 1074, in __threaded_polling
marzban-1     |     self.worker_pool.raise_exceptions()
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/telebot/util.py", line 156, in raise_exceptions
marzban-1     |     raise self.exception_info
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/telebot/util.py", line 100, in run
marzban-1     |     task(*args, **kwargs)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/telebot/__init__.py", line 6395, in _run_middlewares_and_handler
marzban-1     |     result = handler['function'](message)
marzban-1     |   File "/code/app/telegram/handlers/admin.py", line 1996, in search_user
marzban-1     |     get_user_info_text(db_user),
marzban-1     |   File "/code/app/telegram/utils/shared.py", line 53, in get_user_info_text
marzban-1     |     data_left = readable_size(user.data_limit - user.used_traffic) if user.data_limit else "-"
marzban-1     |   File "/code/app/utils/system.py", line 172, in readable_size
marzban-1     |     i = int(math.floor(math.log(size_bytes, 1024)))
marzban-1     | ValueError: math domain error
marzban-1     | "
```

**Comment by esodrevo** [comment]
منم همین مشکل رو دارم

**Comment by ImMohammad20000** [comment]
#1340
