### ISSUE TITLE
Error with Reset User Usage in DEV

### ISSUE THREAD

**Issue by LonUp** [Gozargah/Marzban#1423]
هنگام ریست کردن حجم در اخرین نسخه dev ارور مشاهده میشه . چه از ربات و چه از پنل

![image](https://github.com/user-attachments/assets/0307a121-68e0-4e60-bdeb-2396938d6d26)

```
marzban-1     | ERROR:    Exception in ASGI application
marzban-1     | Traceback (most recent call last):
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2700, in delete
marzban-1     |     state = attributes.instance_state(instance)
marzban-1     | AttributeError: 'NoneType' object has no attribute '_sa_instance_state'
marzban-1     | 
marzban-1     | The above exception was the direct cause of the following exception:
marzban-1     | 
marzban-1     | Traceback (most recent call last):
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
marzban-1     |     result = await app(  # type: ignore[func-returns-value]
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
marzban-1     |     return await self.app(scope, receive, send)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 271, in __call__
marzban-1     |     await super().__call__(scope, receive, send)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 118, in __call__
marzban-1     |     await self.middleware_stack(scope, receive, send)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
marzban-1     |     raise exc
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
marzban-1     |     await self.app(scope, receive, _send)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
marzban-1     |     await self.simple_response(scope, receive, send, request_headers=headers)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
marzban-1     |     await self.app(scope, receive, send)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
marzban-1     |     raise exc
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
marzban-1     |     await self.app(scope, receive, sender)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
marzban-1     |     raise e
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
marzban-1     |     await self.app(scope, receive, send)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
marzban-1     |     await route.handle(scope, receive, send)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
marzban-1     |     await self.app(scope, receive, send)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
marzban-1     |     response = await func(request)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
marzban-1     |     raw_response = await run_endpoint_function(
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
marzban-1     |     return await run_in_threadpool(dependant.call, **values)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
marzban-1     |     return await anyio.to_thread.run_sync(func, *args)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
marzban-1     |     return await get_asynclib().run_sync_in_worker_thread(
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
marzban-1     |     return await future
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
marzban-1     |     result = context.run(func, *args)
marzban-1     |   File "/code/app/routers/user.py", line 167, in reset_user_data_usage
marzban-1     |     dbuser = crud.reset_user_data_usage(db=db, dbuser=dbuser)
marzban-1     |   File "/code/app/db/crud.py", line 554, in reset_user_data_usage
marzban-1     |     db.delete(dbuser.next_plan)
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2702, in delete
marzban-1     |     util.raise_(
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
marzban-1     |     raise exception
marzban-1     | sqlalchemy.orm.exc.UnmappedInstanceError: Class 'builtins.NoneType' is not mapped
```

**Comment by ImMohammad20000** [comment]
fixed #1424

**Comment by ImMohammad20000** [comment]
آپدیت کن ببین حل شد؟

**Comment by LonUp** [comment]
> آپدیت کن ببین حل شد؟

بله حل شد . ممنون
