### ISSUE TITLE
Bug title عدم محاسبه ترافیک یوزر ها

### ISSUE THREAD

**Issue by Jolge100** [Gozargah/Marzban#1435]
مشکلی که دارم اینه که سرور مستر و نود ها به درستی کار می کنه اما اصلا ترافیک یوزر ها محاسبه نمی شه و توی log هم این ارور رو می ده
```
marzban-1     | Job "record_user_usages (trigger: interval[0:00:10], next run at: 2024-11-14 16:49:39 UTC)" raised an exception
marzban-1     | Traceback (most recent call last):
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
marzban-1     |     retval = job.func(*job.args, **job.kwargs)
marzban-1     |   File "/code/app/jobs/record_usages.py", line 154, in record_user_usages
marzban-1     |     for uid, usage in users_usage.items():
marzban-1     | AttributeError: 'list' object has no attribute 'items'
marzban-1     | Job "record_user_usages (trigger: interval[0:00:10], next run at: 2024-11-14 16:49:49 UTC)" raised an exception
marzban-1     | Traceback (most recent call last):
marzban-1     |   File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
marzban-1     |     retval = job.func(*job.args, **job.kwargs)
marzban-1     |   File "/code/app/jobs/record_usages.py", line 154, in record_user_usages
marzban-1     |     for uid, usage in users_usage.items():
marzban-1     | AttributeError: 'list' object has no attribute 'items'
```

**Comment by ImMohammad20000** [comment]
@MuhammadAshouri

**Comment by ImMohammad20000** [comment]
آپدیت کن ببین اوکی شد؟
