### ISSUE TITLE
Crashes while trying to fetch node_logs

### ISSUE THREAD

**Issue by reloadlife** [Gozargah/Marzban#289]
```ERROR:    Exception in ASGI application
marz-marzban-1  | Traceback (most recent call last):
marz-marzban-1  |   File "/code/app/xray/node.py", line 189, in get_logs
marz-marzban-1  |     logs = self.remote.fetch_logs(buf.append)
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/netref.py", line 153, in __getattr__
marz-marzban-1  |     return syncreq(self, consts.HANDLE_GETATTR, name)
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/netref.py", line 63, in syncreq
marz-marzban-1  |     return conn.sync_request(handler, proxy, *args)
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/protocol.py", line 718, in sync_request
marz-marzban-1  |     return _async_res.value
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/async_.py", line 108, in value
marz-marzban-1  |     raise self._obj
marz-marzban-1  | _get_exception_class.<locals>.Derived: cannot access 'fetch_logs'
marz-marzban-1  | 
marz-marzban-1  | ========= Remote Traceback (1) =========
marz-marzban-1  | Traceback (most recent call last):
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/protocol.py", line 356, in _dispatch_request
marz-marzban-1  |     res = self._HANDLERS[handler](self, *args)
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/protocol.py", line 853, in _handle_getattr
marz-marzban-1  |     return self._access_attr(obj, name, (), "_rpyc_getattr", "allow_getattr", getattr)
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/protocol.py", line 780, in _access_attr
marz-marzban-1  |     name = self._check_attr(obj, name, param)
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/rpyc/core/protocol.py", line 770, in _check_attr
marz-marzban-1  |     raise AttributeError(f"cannot access {name!r}")
marz-marzban-1  | AttributeError: cannot access 'fetch_logs'
marz-marzban-1  | 
marz-marzban-1  | 
marz-marzban-1  | During handling of the above exception, another exception occurred:
marz-marzban-1  | 
marz-marzban-1  | Traceback (most recent call last):
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 230, in run_asgi
marz-marzban-1  |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
marz-marzban-1  |     return await self.app(scope, receive, send)
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 271, in __call__
marz-marzban-1  |     await super().__call__(scope, receive, send)
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 118, in __call__
marz-marzban-1  |     await self.middleware_stack(scope, receive, send)
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__
marz-marzban-1  |     await self.app(scope, receive, send)
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 76, in __call__
marz-marzban-1  |     await self.app(scope, receive, send)
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
marz-marzban-1  |     raise exc
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
marz-marzban-1  |     await self.app(scope, receive, sender)
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
marz-marzban-1  |     raise e
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
marz-marzban-1  |     await self.app(scope, receive, send)
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
marz-marzban-1  |     await route.handle(scope, receive, send)
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 341, in handle
marz-marzban-1  |     await self.app(scope, receive, send)
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 82, in app
marz-marzban-1  |     await func(session)
marz-marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 289, in app
marz-marzban-1  |     await dependant.call(**values)
marz-marzban-1  |   File "/code/app/views/node.py", line 97, in node_logs
marz-marzban-1  |     with xray.nodes[node_id].get_logs() as logs:
marz-marzban-1  |   File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
marz-marzban-1  |     return next(self.gen)
marz-marzban-1  |   File "/code/app/xray/node.py", line 201, in get_logs
marz-marzban-1  |     logs.stop()
marz-marzban-1  | UnboundLocalError: local variable 'logs' referenced before assignment
marz-marzban-1  | INFO:     connection closed```

**Comment by SaintShit** [comment]
Hi, this is due to the fact that you node's not updated, however this exception should be handled.
