### ISSUE TITLE
alembic upgrade head

### ISSUE THREAD

**Issue by AminAsa1** [Gozargah/Marzban#395]
Traceback (most recent call last):
  File "/root/Marzban/./app/xray/config.py", line 206, in _resolve_inbounds
    settings['pbk'] = tls_settings['publicKey']
KeyError: 'publicKey'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/alembic/config.py", line 590, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/usr/local/lib/python3.8/dist-packages/alembic/config.py", line 584, in main
    self.run_cmd(cfg, options)
  File "/usr/local/lib/python3.8/dist-packages/alembic/config.py", line 561, in run_cmd
    fn(
  File "/usr/local/lib/python3.8/dist-packages/alembic/command.py", line 322, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/dist-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/Marzban/app/db/migrations/env.py", line 8, in <module>
    from app.db.base import Base
  File "/root/Marzban/./app/__init__.py", line 35, in <module>
    from app import dashboard, jobs, telegram, views  # noqa
  File "/root/Marzban/./app/jobs/__init__.py", line 13, in <module>
    spec.loader.exec_module(importlib.util.module_from_spec(spec))
  File "/root/Marzban/./app/jobs/reset_user_data_usage.py", line 3, in <module>
    from app import logger, scheduler, xray
  File "/root/Marzban/./app/xray/__init__.py", line 26, in <module>
    config = XRayConfig(XRAY_JSON, api_port=api_port)
  File "/root/Marzban/./app/xray/config.py", line 51, in __init__
    self._resolve_inbounds()
  File "/root/Marzban/./app/xray/config.py", line 215, in _resolve_inbounds
    x25519 = core.get_x25519(pvk)
  File "/root/Marzban/./app/xray/core.py", line 45, in get_x25519
    output = subprocess.check_output(cmd, stderr=subprocess.STDOUT).decode('utf-8')
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/xray', 'x25519', '-i', 'MMX7m0Mj3faUstoEm5NBdegeXkHG6ZB78xzBv2n3ZUA']' returned non-zero exit status 2.

**Comment by SaintShit** [comment]
the version of xray installed on your system must be > 1.8.0, so run `xray version` to check that.
