### ISSUE TITLE
Connection errors in nodes

### ISSUE THREAD

**Issue by ImMohammad20000** [Gozargah/Marzban#763]
how to fix node connecting issues?

Any other ideas?

**Comment by ImMohammad20000** [comment]
when node is down som times this logs show in marzban logs


```
marzban-marzban-1     | Job "record_node_usages (trigger: interval[0:00:10], next run at: 2024-01-26 16:37:29 UTC)" raised an exception
marzban-marzban-1     | Traceback (most recent call last):
marzban-marzban-1     |   File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
marzban-marzban-1     |     retval = job.func(*job.args, **job.kwargs)
marzban-marzban-1     |   File "/code/app/jobs/record_usages.py", line 168, in record_node_usages
marzban-marzban-1     |     api_instances[node_id] = node.api
marzban-marzban-1     |   File "/code/app/xray/node.py", line 125, in api
marzban-marzban-1     |     raise ConnectionError("Node is not connected")
marzban-marzban-1     | ConnectionError: Node is not connected
```

**Comment by ImMohammad20000** [comment]
> من فکر نمیکنم rpyc از اول ایده خوبی بوده

اگه فکر بهتری داری بگو پیاده کنیم


من یه باگ تو لاگ ها پیدا کردم که باعث قطعی بود فیکسش کردم ولی هنوز ارور تایم اوت و بقیه ارور ها هست که وضعیتو خیلی آن استیبل کرده😑😑😑

**Comment by m0x61h0x64i** [comment]
https://github.com/Gozargah/Marzban-node/issues/46
