### ISSUE TITLE
حذف نود

### ISSUE THREAD

**Issue by Mowjiii** [Gozargah/Marzban#812]
سلام من وقتی میخوام یکی از نود هامو پاک کنم ارور Something went wrong! میده
راه حل چی هستش؟

**Comment by M03ED** [comment]
لاگ های مرزبان رو از ارسال کنید

**Comment by SaintShit** [comment]
سلام
وقتی با مرورگر مرزبان رو باز دارین، دکمه f12 رو بزنید، به تب network برین و بعد برای حذف نود اقدام کنین. response درخواستی که ساخته میشه و ارور میگیره رو بررسی کنید چه اروری نوشته شده

**Comment by Mowjiii** [comment]
FetchError: 500 Internal Server Error (/api/node/29)


vendor.c2f12c61.js:423 
        
        
       DELETE https://xxxxxxxx/api/node/29 500 (Internal Server Error)
i @ vendor.c2f12c61.js:423
o @ vendor.c2f12c61.js:423
An @ index.fa4c9c0f.js:1
deleteNode @ index.fa4c9c0f.js:1
fn @ vendor.c2f12c61.js:405
P @ vendor.c2f12c61.js:405
YW @ vendor.c2f12c61.js:405
t.executeMutation @ vendor.c2f12c61.js:405
(anonymous) @ vendor.c2f12c61.js:405
Promise.then (async)
t.execute @ vendor.c2f12c61.js:405
n.mutate @ vendor.c2f12c61.js:405
(anonymous) @ vendor.c2f12c61.js:405
onClick @ index.fa4c9c0f.js:1
iV @ vendor.c2f12c61.js:323
aV @ vendor.c2f12c61.js:323
sV @ vendor.c2f12c61.js:323
$_ @ vendor.c2f12c61.js:323
gD @ vendor.c2f12c61.js:323
(anonymous) @ vendor.c2f12c61.js:323
$A @ vendor.c2f12c61.js:326
BL @ vendor.c2f12c61.js:323
a0 @ vendor.c2f12c61.js:323
uA @ vendor.c2f12c61.js:323
SV @ vendor.c2f12c61.js:323

**Comment by Mowjiii** [comment]
> ه موقع حذف کردن نود می گیرید رو بفرستید

فرستادم ک 
![image](https://github.com/Gozargah/Marzban/assets/36294316/c040664c-d6c1-40fa-a473-6587006d2c19)

**Comment by SaintShit** [comment]
> > ه موقع حذف کردن نود می گیرید رو بفرستید
> 
> فرستادم ک ![image](https://private-user-images.githubusercontent.com/36294316/307063824-c040664c-d6c1-40fa-a473-6587006d2c19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MTgzNDEsIm5iZiI6MTcwODYxODA0MSwicGF0aCI6Ii8zNjI5NDMxNi8zMDcwNjM4MjQtYzA0MDY2NGMtZDZjMS00MGZhLWE0NzMtNjU4NzAwNmQyYzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE2MDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNzI4YjM3NTU3ZTZkOTU4ZGY4NzgxN2Y1NDM2NTI2NjQxNWUyNTJkNWM3M2I4NzY5OGFiNjEzOGUxMTgzYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0FXi_78J7KYTWIoLtPX6vXj90kg8q_K8cn1OEA711IQ)

عرض کردم f12 بزنید اروری که درخواست توی اونجا میده رو بفرستین. یه درخواست DELETE به آدرس 
/api/node
ساخته میشه

**Comment by M03ED** [comment]
> > ه موقع حذف کردن نود می گیرید رو بفرستید
> 
> فرستادم ک ![image](https://private-user-images.githubusercontent.com/36294316/307063824-c040664c-d6c1-40fa-a473-6587006d2c19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MTgzNzcsIm5iZiI6MTcwODYxODA3NywicGF0aCI6Ii8zNjI5NDMxNi8zMDcwNjM4MjQtYzA0MDY2NGMtZDZjMS00MGZhLWE0NzMtNjU4NzAwNmQyYzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE2MDc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxNDQwMjdlMmRiYmZhNzNjMGVhMjcxYTZjYTFkMzNjODU5MTRmODY3ZTMyODM1N2QyMDFhODdhY2ZkNWFkMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x6bukCvw0CYVY1RPcyUhhMF5Nm6NH1KZH4-u4XqX81o)

همزمان که تو پنل درخواست میزنید لاگ رو از ترمینال باز کنید
اونجا ارور رو نشون میده ، اون رو کپی و اینجا بفرستید

**Comment by Mowjiii** [comment]
> > > ه موقع حذف کردن نود می گیرید رو بفرستید
> > 
> > 
> > فرستادم ک ![image](https://private-user-images.githubusercontent.com/36294316/307063824-c040664c-d6c1-40fa-a473-6587006d2c19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MTgzNzcsIm5iZiI6MTcwODYxODA3NywicGF0aCI6Ii8zNjI5NDMxNi8zMDcwNjM4MjQtYzA0MDY2NGMtZDZjMS00MGZhLWE0NzMtNjU4NzAwNmQyYzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE2MDc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxNDQwMjdlMmRiYmZhNzNjMGVhMjcxYTZjYTFkMzNjODU5MTRmODY3ZTMyODM1N2QyMDFhODdhY2ZkNWFkMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x6bukCvw0CYVY1RPcyUhhMF5Nm6NH1KZH4-u4XqX81o)
> 
> همزمان که تو پنل درخواست میزنید لاگ رو از ترمینال باز کنید اونجا ارور رو نشون میده ، اون رو کپی و اینجا بفرستید

marzban-1  | INFO:     127.0.0.1:59674 - "DELETE /api/node/29 HTTP/1.1" 500 Internal Server Error
marzban-1  | ERROR:    Exception in ASGI application
marzban-1  | Traceback (most recent call last):
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1880, in _execute_context
marzban-1  |     self.dialect.do_executemany(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 733, in do_executemany
marzban-1  |     cursor.executemany(statement, parameters)
marzban-1  | sqlite3.DatabaseError: database disk image is malformed
marzban-1  | 
marzban-1  | The above exception was the direct cause of the following exception:
marzban-1  | 
marzban-1  | Traceback (most recent call last):
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
marzban-1  |     result = await app(  # type: ignore[func-returns-value]
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
marzban-1  |     return await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 271, in __call__
marzban-1  |     await super().__call__(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 118, in __call__
marzban-1  |     await self.middleware_stack(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
marzban-1  |     raise exc
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
marzban-1  |     await self.app(scope, receive, _send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
marzban-1  |     await self.simple_response(scope, receive, send, request_headers=headers)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
marzban-1  |     await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
marzban-1  |     raise exc
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
marzban-1  |     await self.app(scope, receive, sender)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
marzban-1  |     raise e
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
marzban-1  |     await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
marzban-1  |     await route.handle(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
marzban-1  |     await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
marzban-1  |     response = await func(request)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
marzban-1  |     raw_response = await run_endpoint_function(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
marzban-1  |     return await run_in_threadpool(dependant.call, **values)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
marzban-1  |     return await anyio.to_thread.run_sync(func, *args)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
marzban-1  |     return await get_asynclib().run_sync_in_worker_thread(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
marzban-1  |     return await future
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
marzban-1  |     result = context.run(func, *args)
marzban-1  |   File "/code/app/views/node.py", line 217, in remove_node
marzban-1  |     crud.remove_node(db, dbnode)
marzban-1  |   File "/code/app/db/crud.py", line 619, in remove_node
marzban-1  |     db.commit()
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1451, in commit
marzban-1  |     self._transaction.commit(_to_root=self.future)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 829, in commit
marzban-1  |     self._prepare_impl()
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 808, in _prepare_impl
marzban-1  |     self.session.flush()
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3444, in flush
marzban-1  |     self._flush(objects)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3583, in _flush
marzban-1  |     with util.safe_reraise():
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
marzban-1  |     compat.raise_(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
marzban-1  |     raise exception
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 3544, in _flush
marzban-1  |     flush_context.execute()
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
marzban-1  |     rec.execute(self)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/unitofwork.py", line 667, in execute
marzban-1  |     util.preloaded.orm_persistence.delete_obj(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 343, in delete_obj
marzban-1  |     _emit_delete_statements(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/orm/persistence.py", line 1468, in _emit_delete_statements
marzban-1  |     c = connection._execute_20(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
marzban-1  |     return meth(self, args_10style, kwargs_10style, execution_options)
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
marzban-1  |     return connection._execute_clauseelement(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
marzban-1  |     ret = self._execute_context(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
marzban-1  |     self._handle_dbapi_exception(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
marzban-1  |     util.raise_(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
marzban-1  |     raise exception
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1880, in _execute_context
marzban-1  |     self.dialect.do_executemany(
marzban-1  |   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 733, in do_executemany
marzban-1  |     cursor.executemany(statement, parameters)
marzban-1  | sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed
marzban-1  | [SQL: DELETE FROM node_usages WHERE node_usages.id = ?]
marzban-1  | [parameters: ((10648,), (10657,), (10671,), (10720,), (10734,), (10744,), (10762,), (10785,)  ... displaying 10 of 1512 total bound parameter sets ...  (38262,), (38284,))]
marzban-1  | (Background on this error at: https://sqlalche.me/e/14/4xp6)

**Comment by Mowjiii** [comment]
> > > ه موقع حذف کردن نود می گیرید رو بفرستید
> > 
> > 
> > فرستادم ک ![image](https://private-user-images.githubusercontent.com/36294316/307063824-c040664c-d6c1-40fa-a473-6587006d2c19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MTgzNDEsIm5iZiI6MTcwODYxODA0MSwicGF0aCI6Ii8zNjI5NDMxNi8zMDcwNjM4MjQtYzA0MDY2NGMtZDZjMS00MGZhLWE0NzMtNjU4NzAwNmQyYzE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDE2MDcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmNzI4YjM3NTU3ZTZkOTU4ZGY4NzgxN2Y1NDM2NTI2NjQxNWUyNTJkNWM3M2I4NzY5OGFiNjEzOGUxMTgzYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0FXi_78J7KYTWIoLtPX6vXj90kg8q_K8cn1OEA711IQ)
> 
> عرض کردم f12 بزنید اروری که درخواست توی اونجا میده رو بفرستین. یه درخواست DELETE به آدرس /api/node ساخته میشه

500 (Internal Server Error)

**Comment by Mowjiii** [comment]
راه حلی نداره ؟

**Comment by M03ED** [comment]
> راه حلی نداره ؟

متاسفانه دیتابیس تون به مشکل خورده ، باید مرزبان جدید ران کنید
سعی کنید با دستور زیر بخشی از دیتابیس که یوزرها جزوش هست رو خروجی بگیرید 

```sql
sqlite3 /var/lib/marzban/db.sqlite3 '.dump --data-only' | sed "s/INSERT INTO \([^ ]*\)/REPLACE INTO \`\\1\`/g" | grep -v "REPLACE INTO \`node_user_usages\`" | grep -v "REPLACE INTO \`node_usages\`" | grep -v "REPLACE INTO \`nodes\`" > /tmp/dump.sql
```
اگر این دستور کار نکرد این یکی رو امتحان کنید
```sql
```
