### ISSUE TITLE
maximum number of running instances reached (1)

### ISSUE THREAD

**Issue by parvizx3** [Gozargah/Marzban#892]
**Describe the bug**
I see this in my docker logs.
it's normal?

```logs
marzban-marzban-1  | Execution of job "core_health_check (trigger: interval[0:00:10], next run at: 2024-03-26 10:01:04 UTC)" skipped: maximum number of running instances reached (1)
marzban-marzban-1  | Execution of job "record_user_usages (trigger: interval[0:00:30], next run at: 2024-03-26 10:01:06 UTC)" skipped: maximum number of running instances reached (1)
marzban-marzban-1  | Execution of job "core_health_check (trigger: interval[0:00:10], next run at: 2024-03-26 10:01:14 UTC)" skipped: maximum number of running instances reached (1)
marzban-marzban-1  | Execution of job "record_node_usages (trigger: interval[0:00:10], next run at: 2024-03-26 10:01:16 UTC)" skipped: maximum number of running instances reached (1)
```

**Screenshots**
![image](https://github.com/Gozargah/Marzban/assets/129318294/2ede1f7f-dac7-4981-8cc5-9812afd0cab4)

**Machine details (please complete the following information):**
 - OS: debian 11
- Python version: running 4.9 docker image
- Nodejs version: running 4.9 docker image
- Browser Firefox

**Comment by fodhelper** [comment]
How many nodes do you have?

**Comment by M03ED** [comment]
which version are you using ?

**Comment by parvizx3** [comment]
> which version are you using ?

4.9.0

**Comment by bestkilleriranlod** [comment]
I have a similar problem except that my nodes are restarting every few minutes! Where is the problem?

**Comment by M03ED** [comment]
> I have a similar problem except that my nodes are restarting every few minutes! Where is the problem?

this is not a problem 
but if your using latest version of xray and sniffing is enabled in your config this can cause crashing xray-core

**Comment by bestkilleriranlod** [comment]
> > I have a similar problem except that my nodes are restarting every few minutes! Where is the problem?
> 
> this is not a problem but if your using latest version of xray and sniffing is enabled in your config this can cause crashing xray-core

Should I disable sniffing?

**Comment by M03ED** [comment]
> > > I have a similar problem except that my nodes are restarting every few minutes! Where is the problem?
> > 
> > 
> > this is not a problem but if your using latest version of xray and sniffing is enabled in your config this can cause crashing xray-core
> 
> Should I disable sniffing?

disable it or use lower version of xray

**Comment by H-Alireza** [comment]
I have same problem
All I get it marzban log is this:
marzban-1 | Execution of job "record_node_usages (trigger: interval[0:00:10], next run at: 2024-10-22 16:06:52 UTC)" skipped: maximum number of running instances reached (1)

and my master server configs get unavailable and give handshake error
after I restart marzban it get fixed

**Comment by M03ED** [comment]
> I have same problem
> All I get it marzban log is this:
> marzban-1 | Execution of job "record_node_usages (trigger: interval[0:00:10], next run at: 2024-10-22 16:06:52 UTC)" skipped: maximum number of running instances reached (1)
> 
> and my master server configs get unavailable and give handshake error
> after I restart marzban it get fixed

It's xray problem not marzban

**Comment by mmsh1370** [comment]
من هم دقیقا همین مشکل رو دارم 
با ریست کردن مرزبان حل میشه ولی گاه اچند ساعت بعد مجدد این مشکل به وجود میاد
و نود مستر کهمزرزبان روش نصبه از کار میوفته



marzban-1     | Execution of job "record_node_usages (trigger: interval[0:00:10], next run at: 2024-11-08 18:57:19 UTC)" skipped: maximum number of running instances reached (1)
marzban-1     | Execution of job "record_node_usages (trigger: interval[0:00:10], next run at: 2024-11-08 18:57:39 UTC)" skipped: maximum number of running instances reached (1)
marzban-1     | Execution of job "record_user_usages (trigger: interval[0:00:30], next run at: 2024-11-08 18:57:49 UTC)" skipped: maximum number of running instances reached (1)
marzban-1     | Execution of job "record_node_usages (trigger: interval[0:00:10], next run at: 2024-11-08 18:57:59 UTC)" skipped: maximum number of running instances reached (1)
marzban-1     | Execution of job "record_node_usages (trigger: interval[0:00:10], next run at: 2024-11-08 18:58:19 UTC)" skipped: maximum number of running instances reached (1)
marzban-1     | Execution of job "record_node_usages (trigger: interval[0:00:10], next run at: 2024-11-08 18:58:39 UTC)" skipped: maximum number of running instances reached (1)

**Comment by Non-believer** [comment]
ببخشید شما راه حلی برای حل این مشکل پیدا کردین ؟

**Comment by andrascii** [comment]
Any recommendation to fix it? My panel after some time returns errors like this:
```
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 168, in _do_get
marzban-1  |     raise exc.TimeoutError(
marzban-1  | sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
marzban-1  | ERROR:    Exception in ASGI application
marzban-1  | Traceback (most recent call last):
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
marzban-1  |     result = await app(  # type: ignore[func-returns-value]
marzban-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
marzban-1  |     return await self.app(scope, receive, send)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
marzban-1  |     await super().__call__(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
marzban-1  |     await self.middleware_stack(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
marzban-1  |     raise exc
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
marzban-1  |     await self.app(scope, receive, _send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
marzban-1  |     await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
marzban-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
marzban-1  |     raise exc
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
marzban-1  |     await app(scope, receive, sender)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
marzban-1  |     await self.middleware_stack(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
marzban-1  |     await route.handle(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
marzban-1  |     await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
marzban-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
marzban-1  |     raise exc
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
marzban-1  |     await app(scope, receive, sender)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
marzban-1  |     response = await f(request)
marzban-1  |                ^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 291, in app
marzban-1  |     solved_result = await solve_dependencies(
marzban-1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/dependencies/utils.py", line 632, in solve_dependencies
marzban-1  |     solved = await run_in_threadpool(call, **solved_result.values)
marzban-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
marzban-1  |     return await anyio.to_thread.run_sync(func, *args)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
marzban-1  |     return await get_async_backend().run_sync_in_worker_thread(
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
marzban-1  |     return await future
marzban-1  |            ^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
marzban-1  |     result = context.run(func, *args)
marzban-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/code/app/models/admin.py", line 64, in get_current
marzban-1  |     admin = cls.get_admin(token, db)
marzban-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/code/app/models/admin.py", line 48, in get_admin
marzban-1  |     dbadmin = crud.get_admin(db, payload['username'])
marzban-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/code/app/db/crud.py", line 915, in get_admin
marzban-1  |     return db.query(Admin).filter(Admin.username == username).first()
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2728, in first
marzban-1  |     return self.limit(1)._iter().first()  # type: ignore
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
marzban-1  |     result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
marzban-1  |                                                   ^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
marzban-1  |     return self._execute_internal(
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2237, in _execute_internal
marzban-1  |     conn = self._connection_for_bind(bind)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2106, in _connection_for_bind
marzban-1  |     return trans._connection_for_bind(engine, execution_options)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "<string>", line 2, in _connection_for_bind
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
marzban-1  |     ret_value = fn(self, *arg, **kw)
marzban-1  |                 ^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1189, in _connection_for_bind
marzban-1  |     conn = bind.connect()
marzban-1  |            ^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3278, in connect
marzban-1  |     return self._connection_cls(self)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
marzban-1  |     self._dbapi_connection = engine.raw_connection()
marzban-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3302, in raw_connection
marzban-1  |     return self.pool.connect()
marzban-1  |            ^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
marzban-1  |     return _ConnectionFairy._checkout(self)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
marzban-1  |     fairy = _ConnectionRecord.checkout(pool)
marzban-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
marzban-1  |     rec = pool._do_get()
marzban-1  |           ^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 168, in _do_get
marzban-1  |     raise exc.TimeoutError(
marzban-1  | sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
marzban-1  | ERROR:    Exception in ASGI application
marzban-1  | Traceback (most recent call last):
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
marzban-1  |     result = await app(  # type: ignore[func-returns-value]
marzban-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
marzban-1  |     return await self.app(scope, receive, send)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
marzban-1  |     await super().__call__(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
marzban-1  |     await self.middleware_stack(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
marzban-1  |     raise exc
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
marzban-1  |     await self.app(scope, receive, _send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
marzban-1  |     await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
marzban-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
marzban-1  |     raise exc
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
marzban-1  |     await app(scope, receive, sender)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
marzban-1  |     await self.middleware_stack(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
marzban-1  |     await route.handle(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
marzban-1  |     await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
marzban-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
marzban-1  |     raise exc
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
marzban-1  |     await app(scope, receive, sender)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
marzban-1  |     response = await f(request)
marzban-1  |                ^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 291, in app
marzban-1  |     solved_result = await solve_dependencies(
marzban-1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/dependencies/utils.py", line 632, in solve_dependencies
marzban-1  |     solved = await run_in_threadpool(call, **solved_result.values)
marzban-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
marzban-1  |     return await anyio.to_thread.run_sync(func, *args)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
marzban-1  |     return await get_async_backend().run_sync_in_worker_thread(
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
marzban-1  |     return await future
marzban-1  |            ^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
marzban-1  |     result = context.run(func, *args)
marzban-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/code/app/models/admin.py", line 64, in get_current
marzban-1  |     admin = cls.get_admin(token, db)
marzban-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/code/app/models/admin.py", line 48, in get_admin
marzban-1  |     dbadmin = crud.get_admin(db, payload['username'])
marzban-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/code/app/db/crud.py", line 915, in get_admin
marzban-1  |     return db.query(Admin).filter(Admin.username == username).first()
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2728, in first
marzban-1  |     return self.limit(1)._iter().first()  # type: ignore
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
marzban-1  |     result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
marzban-1  |                                                   ^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
marzban-1  |     return self._execute_internal(
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2237, in _execute_internal
marzban-1  |     conn = self._connection_for_bind(bind)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2106, in _connection_for_bind
marzban-1  |     return trans._connection_for_bind(engine, execution_options)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "<string>", line 2, in _connection_for_bind
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
marzban-1  |     ret_value = fn(self, *arg, **kw)
marzban-1  |                 ^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1189, in _connection_for_bind
marzban-1  |     conn = bind.connect()
marzban-1  |            ^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3278, in connect
marzban-1  |     return self._connection_cls(self)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
marzban-1  |     self._dbapi_connection = engine.raw_connection()
marzban-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3302, in raw_connection
marzban-1  |     return self.pool.connect()
marzban-1  |            ^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
marzban-1  |     return _ConnectionFairy._checkout(self)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
marzban-1  |     fairy = _ConnectionRecord.checkout(pool)
marzban-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
marzban-1  |     rec = pool._do_get()
marzban-1  |           ^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 168, in _do_get
marzban-1  |     raise exc.TimeoutError(
marzban-1  | sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
marzban-1  | Execution of job "record_user_usages (trigger: interval[0:00:10], next run at: 2025-06-18 12:20:24 UTC)" skipped: maximum number of running instances reached (1)
marzban-1  | Execution of job "record_node_usages (trigger: interval[0:00:30], next run at: 2025-06-18 12:20:24 UTC)" skipped: maximum number of running instances reached (1)
marzban-1  | ERROR:    Exception in ASGI application
marzban-1  | Traceback (most recent call last):
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
marzban-1  |     result = await app(  # type: ignore[func-returns-value]
marzban-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
marzban-1  |     return await self.app(scope, receive, send)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
marzban-1  |     await super().__call__(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 113, in __call__
marzban-1  |     await self.middleware_stack(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 187, in __call__
marzban-1  |     raise exc
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 165, in __call__
marzban-1  |     await self.app(scope, receive, _send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
marzban-1  |     await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
marzban-1  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
marzban-1  |     raise exc
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
marzban-1  |     await app(scope, receive, sender)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 715, in __call__
marzban-1  |     await self.middleware_stack(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 735, in app
marzban-1  |     await route.handle(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 288, in handle
marzban-1  |     await self.app(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 76, in app
marzban-1  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 62, in wrapped_app
marzban-1  |     raise exc
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 51, in wrapped_app
marzban-1  |     await app(scope, receive, sender)
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 73, in app
marzban-1  |     response = await f(request)
marzban-1  |                ^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 291, in app
marzban-1  |     solved_result = await solve_dependencies(
marzban-1  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/fastapi/dependencies/utils.py", line 632, in solve_dependencies
marzban-1  |     solved = await run_in_threadpool(call, **solved_result.values)
marzban-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
marzban-1  |     return await anyio.to_thread.run_sync(func, *args)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
marzban-1  |     return await get_async_backend().run_sync_in_worker_thread(
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
marzban-1  |     return await future
marzban-1  |            ^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
marzban-1  |     result = context.run(func, *args)
marzban-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/code/app/models/admin.py", line 64, in get_current
marzban-1  |     admin = cls.get_admin(token, db)
marzban-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/code/app/models/admin.py", line 48, in get_admin
marzban-1  |     dbadmin = crud.get_admin(db, payload['username'])
marzban-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/code/app/db/crud.py", line 915, in get_admin
marzban-1  |     return db.query(Admin).filter(Admin.username == username).first()
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2728, in first
marzban-1  |     return self.limit(1)._iter().first()  # type: ignore
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
marzban-1  |     result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
marzban-1  |                                                   ^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
marzban-1  |     return self._execute_internal(
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2237, in _execute_internal
marzban-1  |     conn = self._connection_for_bind(bind)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2106, in _connection_for_bind
marzban-1  |     return trans._connection_for_bind(engine, execution_options)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "<string>", line 2, in _connection_for_bind
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
marzban-1  |     ret_value = fn(self, *arg, **kw)
marzban-1  |                 ^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1189, in _connection_for_bind
marzban-1  |     conn = bind.connect()
marzban-1  |            ^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3278, in connect
marzban-1  |     return self._connection_cls(self)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
marzban-1  |     self._dbapi_connection = engine.raw_connection()
marzban-1  |                              ^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3302, in raw_connection
marzban-1  |     return self.pool.connect()
marzban-1  |            ^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
marzban-1  |     return _ConnectionFairy._checkout(self)
marzban-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
marzban-1  |     fairy = _ConnectionRecord.checkout(pool)
marzban-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
marzban-1  |     rec = pool._do_get()
marzban-1  |           ^^^^^^^^^^^^^^
marzban-1  |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/impl.py", line 168, in _do_get
marzban-1  |     raise exc.TimeoutError(
marzban-1  | sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
marzban-1  | INFO:     127.0.0.1:33464 - "GET /api/users/ HTTP/1.1" 307 Temporary Redirect
```

And REST API doesnt work

**Comment by andrascii** [comment]
I spend more than $3000 on ads and now this panel just crashes!!!
